apiVersion: core.crd.test.com/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: i-operator
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  # TODO(user): Add fields here
  image: xxxxx/infra/nginx:1.25.5
  enabled: true
